services:
  blue_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blue_app
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  green_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green_app
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8001"

  cadvisor:
    image: google/cadvisor:canary
    container_name: cadvisor-backend-1
    ports:
      - "5500:8080"  # 호스트 포트를 5500으로 매핑
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro" #디스크 I/O 관련 메트릭
    networks:
      - nextloop_network
    restart: always

networks:
  nextloop_network:
    driver: bridge
