version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 80"

  cadvisor:
    image: google/cadvisor:canary
    container_name: cadvisor-backend-1
    ports:
      - "5500:8080"  # 호스트 포트를 5500으로 매핑
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro" #디스크 I/O 관련 메트릭
    networks:
      - nextloop_network
    restart: always

networks:
  nextloop_network:
    external: true
