version: '3.8'
services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: mariadb_container
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile.zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app_network

  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - app_network

volumes:
  mariadb_data:

networks:
  app_network:
    driver: bridge