version: '3.8'

services:
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    command:
      - "--kafka.server=10.178.0.3:9092"  # Kafka 클러스터 1번 브로커
      - "--kafka.server=10.178.0.7:9092"  # Kafka 클러스터 2번 브로커
      - "--kafka.server=10.178.0.9:9092"  # Kafka 클러스터 3번 브로커
    ports:
      - "9308:9308"  # Prometheus가 스크랩할 Kafka Exporter의 포트
    networks:
      - kafka_network
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일 마운트
      - prometheus-storage:/prometheus  # Prometheus 데이터를 저장할 볼륨
    depends_on:
      - kafka-exporter
    networks:
      - kafka_network
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always
    networks:
      - kafka_network

volumes:
  prometheus-storage:
  grafana-storage:

networks:
  kafka_network:
    name: kafka_network
    driver: bridge